# Generated by Django 4.0.4 on 2022-04-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_movie_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="alternative_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
