# Generated by Django 4.0.4 on 2022-06-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_movie_alternative_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="imdb_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
