# Generated by Django 4.0.4 on 2022-06-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
