# Generated by Django 4.0.4 on 2022-04-13 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinema",
            name="region",
        ),
    ]
