# Generated by Django 4.0.4 on 2022-04-13 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0002_remove_cinema_region"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="chain",
            field=models.CharField(
                choices=[
                    ("CineHoyts", "CineHoyts"),
                    ("Cinemark", "Cinemark"),
                    ("Cineplanet", "Cineplanet"),
                    ("Independent", "Independent"),
                    ("Muvix", "Muvix"),
                ],
                max_length=255,
            ),
        ),
    ]
