# Generated by Django 4.0.4 on 2022-04-13 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0004_schedule_delete_schedules"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cinema",
            name="city",
        ),
    ]
