# Generated by Django 4.0.4 on 2022-04-14 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_alter_movie_title"),
        ("cinema", "0006_rename_title_cinema_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cinema",
            name="link",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="cinema",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="movie",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="movie.movie",
            ),
        ),
    ]
