# Generated by Django 4.0.4 on 2022-04-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0007_alter_cinema_link_alter_cinema_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="datetime",
        ),
        migrations.AddField(
            model_name="schedule",
            name="showing_datetime",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="week",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
