# Generated by Django 4.0.4 on 2022-04-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cinema", "0008_remove_schedule_datetime_schedule_showing_datetime_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Schedule",
        ),
    ]
