# Generated by Django 4.0.4 on 2022-04-14 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_movie_alternative_title"),
        ("cinema", "0009_delete_schedule"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showing_datetime", models.CharField(max_length=255)),
                ("week", models.DateTimeField()),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="cinema.cinema",
                    ),
                ),
                (
                    "movie",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
    ]
