# Generated by Django 4.0.4 on 2022-04-14 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_movie_alternative_title"),
        ("cinema", "0011_cinema_keyword"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="movie.movie",
            ),
        ),
    ]
