# Generated by Django 4.0.4 on 2022-06-18 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movie_imdb_id"),
        ("cinema", "0012_alter_schedule_movie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Showing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("showing_date", models.CharField(max_length=255)),
                ("showing_datetime", models.CharField(max_length=255)),
                (
                    "cinema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showings",
                        to="cinema.cinema",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="showings",
                        to="movie.movie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Town",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("keyword", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(max_length=255, unique=True)),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                ("zone", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.AddField(
            model_name="cinema",
            name="town",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cinemas",
                to="cinema.town",
            ),
        ),
    ]
